# Generated by Django 2.0.7 on 2018-07-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
